# Generated by Django 3.2.2 on 2021-05-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('canceled', 'Canceled')], max_length=20)),
                ('requestType', models.CharField(choices=[('database', 'Database'), ('microsoft-365', 'Microsoft 365'), ('customer-platform', 'Customer Platform'), ('power-bi', 'Power BI'), ('wordpress-site', 'WordPress Site')], max_length=20)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('test', 'Testing'), ('production', 'Production')], max_length=20)),
                ('entryDate', models.DateTimeField()),
                ('targetDate', models.DateTimeField()),
                ('shortDescription', models.CharField(max_length=50)),
                ('longDescription', models.CharField(max_length=250)),
                ('changeImpact', models.CharField(max_length=250)),
                ('fileUpload', models.FileField(upload_to='supplemental')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignee', to='login_app.user', verbose_name='Assignee')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requestor', to='login_app.user', verbose_name='Requestor')),
            ],
        ),
    ]
