# Generated by Django 3.2.2 on 2021-05-13 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assignee', to='login_app.user', verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='change',
            name='fileUpload',
            field=models.FileField(blank=True, null=True, upload_to='supplemental'),
        ),
    ]
