# Generated by Django 3.2.2 on 2021-05-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210512_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='changeImpact',
            field=models.CharField(max_length=250, verbose_name='Change Impact'),
        ),
        migrations.AlterField(
            model_name='change',
            name='entryDate',
            field=models.DateField(verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='change',
            name='environment',
            field=models.CharField(choices=[('development', 'Development'), ('test', 'Testing'), ('production', 'Production')], max_length=20, verbose_name='Enviornment'),
        ),
        migrations.AlterField(
            model_name='change',
            name='fileUpload',
            field=models.FileField(blank=True, null=True, upload_to='supplemental', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='change',
            name='longDescription',
            field=models.CharField(max_length=250, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='change',
            name='requestType',
            field=models.CharField(choices=[('database', 'Database'), ('microsoft-365', 'Microsoft 365'), ('customer-platform', 'Customer Platform'), ('power-bi', 'Power BI'), ('wordpress-site', 'WordPress Site')], max_length=20, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='change',
            name='shortDescription',
            field=models.CharField(max_length=50, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='change',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('canceled', 'Canceled')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='change',
            name='targetDate',
            field=models.DateField(verbose_name='Target End Date'),
        ),
    ]
