# Generated by Django 3.2.2 on 2021-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210512_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status'),
        ),
    ]
