# Generated by Django 3.2.2 on 2021-05-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_change_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='environment',
            field=models.CharField(choices=[('development', 'Development'), ('test', 'Testing'), ('production', 'Production')], max_length=20, verbose_name='Environment'),
        ),
    ]
