# Generated by Django 3.2.2 on 2021-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_change_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='requestType',
            field=models.CharField(choices=[('database', 'Database'), ('microsoft-365', 'Microsoft 365'), ('customer-platform', 'Customer Platform'), ('power-bi', 'Power BI'), ('wordpress-site', 'WordPress Site')], max_length=30, verbose_name='Request Type'),
        ),
    ]
