# Generated by Django 3.2.2 on 2021-05-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_change_requesttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='completionDate',
            field=models.DateField(default='2021-05-01', verbose_name='Completion Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change',
            name='completionNotes',
            field=models.CharField(default='Notes', max_length=250, verbose_name='Completion Notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='low', max_length=20, verbose_name='Priority'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='change',
            name='requestType',
            field=models.CharField(choices=[('database', 'Database'), ('microsoft-365', 'Microsoft 365'), ('customer-platform', 'Customer Platform'), ('power-bi', 'Power BI'), ('wordpress-site', 'WordPress Site'), ('change-management-system', 'Change Management System')], max_length=30, verbose_name='Request Type'),
        ),
    ]
