# Generated by Django 3.2.2 on 2021-05-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210514_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='completionDate',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='change',
            name='completionNotes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Completion Notes'),
        ),
    ]
